import DataContext from '@/utils/DataContext';
import bootstrap from '../node_modules/bootstrap/dist/css/bootstrap.min.css';
import Link from 'next/link';


export const metadata = {
  title: 'The Movie Database',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body suppressHydrationWarning style={{ backgroundColor: "orange" }}>
        <Link href={"/"} style={{ textDecoration: "none", color: "#000" }}><h1 className='display-1 text-center mt-4' style={{ fontWeight: "800" }}>The Movie Database</h1></Link>
        {children}
        <h5 className='text-center m-5'>Made with ❤️ by Prateek Nashine.</h5>
      </body>
    </html>
  )
}
